apiVersion: app.appvia.io/v2beta1
kind: Application
metadata:
  name: app-name-placeholder
spec:
  cloud: azure
  components:
  - container:
      expose: true
      # TODO: need to change the repo to the one created by the create-wf-app pipeline
      image: ghcr.io/digital-garage-icl/repo-name-placeholder:latest
      port: 8080
      tls: true
    name: component-name-placeholder
    type: Container
  name: app-name-placeholder